import { Report, Reward, User, ViolationType } from './types';

export const VIOLATION_TYPES: ViolationType[] = [
  { id: 'v1', label: 'Driving without Driving Licence', defaultPoints: 50 },
  { id: 'v2', label: 'Riding without Helmet', defaultPoints: 20 },
  { id: 'v3', label: 'Not Wearing Seatbelt', defaultPoints: 15 },
  { id: 'v4', label: 'Signal Jumping / Red Light Violation', defaultPoints: 25 },
  { id: 'v5', label: 'Wrong-Side Driving', defaultPoints: 30 },
  { id: 'v6', label: 'Over-speeding', defaultPoints: 50 },
  { id: 'v7', label: 'Using Mobile Phone while Driving', defaultPoints: 35 },
  { id: 'v8', label: 'Drunk and Drive', defaultPoints: 100 },
  { id: 'v9', label: 'Driving without Insurance', defaultPoints: 40 },
  { id: 'v10', label: 'Illegal Parking / No-Parking Zone', defaultPoints: 10 },
  { id: 'v11', label: 'Triple Riding', defaultPoints: 30 },
];

export const MOCK_REWARDS: Reward[] = [
  {
    id: 'r1',
    title: 'Sports Training Pass',
    description: 'One-month coaching access for any sport at local complexes.',
    pointsCost: 70,
    imageUrl: 'https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&q=80&w=800',
    category: 'HEALTH',
  },
  {
    id: 'r2',
    title: 'Library Membership',
    description: 'One-year free digital & physical library access.',
    pointsCost: 80,
    imageUrl: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&q=80&w=800',
    category: 'EDUCATION',
  },
  {
    id: 'r3',
    title: 'Tech Accessories Voucher',
    description: 'Discount on headphones, mouse, or keyboard at partner stores.',
    pointsCost: 100,
    imageUrl: 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?auto=format&fit=crop&q=80&w=800',
    category: 'SHOPPING',
  },
  {
    id: 'r4',
    title: '₹100 Fuel Coupon',
    description: 'Valid at any Indian Oil petrol pump for petrol or diesel.',
    pointsCost: 100,
    imageUrl: '/rewards/fuel.jpg',
    category: 'FUEL',
  },
  {
    id: 'r5',
    title: 'Free Metro/Bus Pass',
    description: 'Unlimited city travel for one week on public transit.',
    pointsCost: 110,
    imageUrl: '/rewards/metro.jpg',
    category: 'TRAVEL',
  },
  {
    id: 'r6',
    title: 'Mobile Recharge Cashback',
    description: 'Instant cashback on prepaid/postpaid recharge.',
    pointsCost: 90,
    imageUrl: '/rewards/airtel.jpg',
    category: 'SERVICES',
  },
  {
    id: 'r7',
    title: 'Insurance Discount Pass',
    description: 'Get up to 10% off on vehicle insurance renewal.',
    pointsCost: 200,
    imageUrl: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&q=80&w=800',
    category: 'INSURANCE',
  },
  {
    id: 'r8',
    title: 'Medicine Discount Card',
    description: 'Save on monthly medical purchases at pharmacy chains.',
    pointsCost: 80,
    imageUrl: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?auto=format&fit=crop&q=80&w=800',
    category: 'HEALTH',
  },
  {
    id: 'r9',
    title: 'Priority Government Service',
    description: 'Fast-track service at select civic offices (RTO, Municipal).',
    pointsCost: 100,
    imageUrl: '/rewards/services.jpg',
    category: 'SERVICES',
  },
  {
    id: 'r10',
    title: 'Family Movie Pass',
    description: 'Enjoy a movie night with family at discounted prices.',
    pointsCost: 140,
    imageUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&q=80&w=800',
    category: 'ENTERTAINMENT',
  },
];

export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    name: 'Karl Arvindraj',
    email: 'arvindrajkarl@gmail.com',
    role: 'CITIZEN',
    points: 45,
    avatarUrl: '/Users/KarlUser.jpg',
    password: '123',
  },
  {
    id: 'u2',
    name: 'Vilasni',
    email: 'vilasni@example.com',
    role: 'CITIZEN',
    points: 120,
    avatarUrl: 'https://ui-avatars.com/api/?name=Vilasni&background=E91E63&color=fff',
    password: 'password123',
  },
  {
    id: 'u3',
    name: 'Rupashree',
    email: 'rupashree@example.com',
    role: 'CITIZEN',
    points: 85,
    avatarUrl: 'https://ui-avatars.com/api/?name=Rupashree&background=4CAF50&color=fff',
    password: 'password123',
  },
  {
    id: 'a1',
    name: 'Officer Allwin',
    email: 'admin@civiceye.gov',
    role: 'ADMIN',
    points: 0,
    avatarUrl: '/Users/AllwinOfficer.jpg',
    password: 'adminpassword',
  },
];

const daysAgo = (days: number) =>
  new Date(Date.now() - 86400000 * days).toISOString();

export const MOCK_REPORTS: Report[] = [
  {
    id: 'rep_002',
    userId: 'u1',
    userName: 'Karl Arvindraj',
    violationTypes: ['Wrong-Side Driving'],
    vehicleNumber: 'TN 01 XX 9999',
    location: 'Nungambakkam High Road, Chennai',
    description: 'Vehicle drove against traffic and entered a one-way lane during peak hours.',
    timestamp: new Date(Date.now() - 3600000 * 2).toISOString(),
    status: 'PENDING',
    imageUrl: '/mockReport/oneway2.jpg',
  },
  {
    id: 'rep_003',
    userId: 'u2',
    userName: 'Vilasni',
    violationTypes: ['Wrong-Side Driving'],
    vehicleNumber: 'TN 09 AZ 7777',
    location: 'Anna Salai, Chennai',
    description: 'Rider and pillion were without helmets while riding on the wrong side of the road.',
    timestamp: new Date(Date.now() - 7200000).toISOString(),
    status: 'PENDING',
    imageUrl: '/mockReport/oneway.jpg',
  },
  {
    id: 'rep_005',
    userId: 'u3',
    userName: 'Rupashree',
    violationTypes: ['Illegal Parking / No-Parking Zone'],
    vehicleNumber: 'TN 07 CK 1122',
    location: 'T. Nagar, Chennai',
    description: 'Vehicle parked blocking a designated bus stop and pedestrian pathway.',
    timestamp: daysAgo(0),
    status: 'PENDING',
    imageUrl: '/mockReport/NoParking.jpg',
  },
  {
    id: 'rep_006',
    userId: 'u1',
    userName: 'Karl Arvindraj',
    violationTypes: ['Illegal Parking / No-Parking Zone'],
    vehicleNumber: 'TN 01 AF 4923',
    location: 'Mount Road (Anna Salai), Chennai',
    description: 'Vehicle parked against traffic flow on a major arterial road.',
    timestamp: daysAgo(0),
    status: 'PENDING',
    imageUrl: '/mockReport/NoParking.jpg',
  },
  {
    id: 'rep_007',
    userId: 'u2',
    userName: 'Vilasni',
    violationTypes: ['Using Mobile Phone while Driving'],
    vehicleNumber: 'TN 10 UB 2828',
    location: 'Adyar, Chennai',
    description: 'Driver was observed using a mobile phone while negotiating a turn.',
    timestamp: daysAgo(1),
    status: 'PENDING',
    imageUrl:
      'https://images.unsplash.com/photo-1512428559087-560fa0db7901?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'rep_001',
    userId: 'u1',
    userName: 'Karl Arvindraj',
    violationTypes: ['Wrong-Side Driving'],
    vehicleNumber: 'TN 01 AB 1234',
    location: 'Nungambakkam, Chennai',
    description: 'Vehicle parked in front of a fire hydrant and obstructing emergency access.',
    timestamp: daysAgo(2),
    status: 'APPROVED',
    imageUrl: '/mockReport/oneway.jpg',
    rewardPoints: 10,
    adminComment: 'Violation confirmed. Challan issued.',
  },
  {
    id: 'rep_008',
    userId: 'u3',
    userName: 'Rupashree',
    violationTypes: ['Not Wearing Seatbelt', 'Using Mobile Phone while Driving'],
    vehicleNumber: 'TN 07 MN 1212',
    location: 'Velachery Main Road, Chennai',
    description: 'Driver not wearing seatbelt and also seen handling phone while on a busy road.',
    timestamp: daysAgo(3),
    status: 'APPROVED',
    imageUrl:
      'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?auto=format&fit=crop&q=80&w=800',
    rewardPoints: 50,
    adminComment: 'Evidence clear. Approved.',
  },
  {
    id: 'rep_009',
    userId: 'u2',
    userName: 'Vilasni',
    violationTypes: ['Over-speeding'],
    vehicleNumber: 'TN 11 BB 5555',
    location: 'OMR Bypass Road, Chennai',
    description: 'Reckless speeding in a 40 km/h zone with unsafe overtakes.',
    timestamp: daysAgo(4),
    status: 'APPROVED',
    imageUrl:
      'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&q=80&w=800',
    rewardPoints: 25,
    adminComment:
      'Speed radar confirmation pending, but visual evidence supports reckless driving claim.',
  },
  {
    id: 'rep_010',
    userId: 'u1',
    userName: 'Karl Arvindraj',
    violationTypes: ['Riding without Helmet'],
    vehicleNumber: 'TN 02 JK 9090',
    location: 'T. Nagar High Road, Chennai',
    description: 'Rider not wearing helmet while riding through a busy junction.',
    timestamp: daysAgo(5),
    status: 'APPROVED',
    imageUrl: '/mockReport/nohelmet.jpg',
    rewardPoints: 20,
    adminComment: 'Approved.',
  },
  {
    id: 'rep_004',
    userId: 'u3',
    userName: 'Rupashree',
    violationTypes: ['Illegal Parking / No-Parking Zone'],
    vehicleNumber: 'TN 01 AD 1111',
    location: 'Egmore, Chennai',
    description: 'Vehicle parked in what appears to be a restricted no-parking area near a public facility.',
    timestamp: daysAgo(1),
    status: 'REJECTED',
    imageUrl:
      'https://images.unsplash.com/photo-1506544777-64cfbe1142df?auto=format&fit=crop&q=80&w=800',
    adminComment:
      'Area is a designated parking zone on weekends. Report invalid.',
    rewardPoints: 0,
  },
  {
    id: 'rep_011',
    userId: 'u2',
    userName: 'Vilasni',
    violationTypes: ['Drunk and Drive'],
    vehicleNumber: 'TN 07 Z 0001',
    location: 'Tiruvanmiyur, Chennai',
    description: 'Driver appears intoxicated and is swerving across lanes.',
    timestamp: daysAgo(2),
    status: 'REJECTED',
    imageUrl:
      'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&q=80&w=800',
    adminComment:
      'Visual evidence insufficient to prove intoxication. Field officer required.',
    rewardPoints: 0,
  },
  {
    id: 'rep_012',
    userId: 'u1',
    userName: 'Karl Arvindraj',
    violationTypes: ['Signal Jumping / Red Light Violation'],
    vehicleNumber: 'Unknown',
    location: 'Chennai (location not clearly visible in image)',
    description: 'Red car observed jumping a signal; vehicle plate not legible in the photo.',
    timestamp: daysAgo(3),
    status: 'REJECTED',
    imageUrl: '/mockReport/traffic.png',
    adminComment:
      'Vehicle number plate not visible in image. Cannot process.',
    rewardPoints: 0,
  },
];
